### ISSUE TITLE
Crashes Wordpress

### ISSUE THREAD

**Issue by mcdragonsi** [SchumacherFM/wordpress-to-hugo-exporter#84] opened 2020-06-21 16:00 UTC
Uploaded the addon, updated php.ini, activated the addon.
When I run the tool it crashes the wordpress app. 
The error log seems to refer to issues with the FastCGI module

`(104)Connection reset by peer: AH10143: FastCGI: comm with server "/homez.32/mcdowelljp/www/blog/wp-admin/export.php" aborted: read failed, referer: https://mydomain.com/wp-admin/tools.php
AH10149: FastCGI: incomplete headers (0 bytes) received from server "/homez.32/mcdowelljp/www/blog/wp-admin/export.php", referer: https://mydomain.com/wp-admin/tools.php
AH10157: FastCGI: An error happened during Fastcgi processing, fallback to CGI, referer: https://mydomain.com/wp-admin/tools.php
End of script output before headers: export.php, referer: https://mydomain.com/wp-admin/tools.php`

**Comment by SchumacherFM** [comment] 2020-06-22 08:55
Thanks for reporting. I have no idea. Maybe someone knows something. Otherwise google for the errors `AH10149: FastCGI: incomplete headers` or `Connection reset by peer: AH10143`

**Comment by DanielRuf** [comment] 2021-08-07 18:07
This is probably caused by some firewall or security solution on the side of the hosting provider.

**Comment by SchumacherFM** [comment] 2021-08-10 18:27
seems like it has been solved, so closing. I can reopen on request.

**Closed by SchumacherFM** 2021-08-10 18:27 UTC
Labels: help wanted
